import { timestamp, varchar } from 'drizzle-orm/pg-core'

/**
 * Options for document columns
 */
export interface DocumentColumnOptions {
	/** Whether i18n is enabled */
	hasI18n: boolean
	/** Whether versioning is enabled */
	hasVersioning: boolean
}

/**
 * Document status enum values
 */
export const DOCUMENT_STATUS = {
	DRAFT: 'draft',
	PUBLISHED: 'published',
	ARCHIVED: 'archived',
} as const

export type DocumentStatus =
	(typeof DOCUMENT_STATUS)[keyof typeof DOCUMENT_STATUS]

/**
 * Default locale
 */
export const DEFAULT_LOCALE = 'en'

/**
 * Apply document columns for i18n and versioning support.
 * This mirrors the Mongoose document plugin behavior.
 *
 * Adds the following columns:
 * - documentId: Groups all locale variants and versions of the same logical document
 * - locale: The locale of this document variant (e.g., 'en', 'pt-BR')
 * - status: The status of this document ('draft', 'published', 'archived')
 * - publishedAt: When this document was published (if applicable)
 */
export function applyDocumentColumns(
	options: DocumentColumnOptions,
): Record<string, any> {
	const columns: Record<string, any> = {}

	if (options.hasI18n || options.hasVersioning) {
		// documentId groups all locale/version variants
		// Using varchar(36) to support the short string IDs generated by the application
		columns.documentId = varchar('document_id', { length: 36 }).notNull()

		// locale for i18n support
		columns.locale = varchar('locale', { length: 10 })
			.notNull()
			.default(DEFAULT_LOCALE)

		// status for versioning/publishing workflow
		columns.status = varchar('status', { length: 20 })
			.notNull()
			.default(DOCUMENT_STATUS.DRAFT)

		// publishedAt for tracking when published
		columns.publishedAt = timestamp('published_at')
	}

	return columns
}

/**
 * Check if a record is a draft
 */
export function isDraft(record: { status?: string }): boolean {
	return record.status === DOCUMENT_STATUS.DRAFT
}

/**
 * Check if a record is published
 */
export function isPublished(record: { status?: string }): boolean {
	return record.status === DOCUMENT_STATUS.PUBLISHED
}
