import { resolve } from 'node:path'
import { defineConfig } from 'tsup'

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		'components/index': 'src/components/index.ts',
		'components/atoms/index': 'src/components/atoms/index.ts',
		'components/molecules/index': 'src/components/molecules/index.ts',
		'components/molecules/hook-form/index':
			'src/components/molecules/hook-form/index.ts',
		'components/organisms/index': 'src/components/organisms/index.ts',
		'components/organisms/app-layout/index':
			'src/components/organisms/app-layout/index.ts',
		'components/organisms/data-table/index':
			'src/components/organisms/data-table/index.ts',
		'hooks/index': 'src/hooks/index.ts',
		'lib/index': 'src/lib/index.ts',
		'services/index': 'src/services/index.ts',
	},
	format: ['cjs', 'esm'],
	dts: true,
	splitting: false,
	sourcemap: true,
	clean: true,
	external: [
		'react',
		'react-dom',
		'react-router-dom',
		'@radix-ui/react-accordion',
		'@radix-ui/react-alert-dialog',
		'@radix-ui/react-aspect-ratio',
		'@radix-ui/react-avatar',
		'@radix-ui/react-checkbox',
		'@radix-ui/react-collapsible',
		'@radix-ui/react-context-menu',
		'@radix-ui/react-dialog',
		'@radix-ui/react-dropdown-menu',
		'@radix-ui/react-hover-card',
		'@radix-ui/react-label',
		'@radix-ui/react-menubar',
		'@radix-ui/react-navigation-menu',
		'@radix-ui/react-popover',
		'@radix-ui/react-progress',
		'@radix-ui/react-radio-group',
		'@radix-ui/react-scroll-area',
		'@radix-ui/react-select',
		'@radix-ui/react-separator',
		'@radix-ui/react-slider',
		'@radix-ui/react-slot',
		'@radix-ui/react-switch',
		'@radix-ui/react-tabs',
		'@radix-ui/react-toast',
		'@radix-ui/react-toggle',
		'@radix-ui/react-toggle-group',
		'@radix-ui/react-tooltip',
		'@tanstack/react-table',
		'@dnd-kit/core',
		'@dnd-kit/modifiers',
		'@dnd-kit/sortable',
		'@dnd-kit/utilities',
		'class-variance-authority',
		'clsx',
		'cmdk',
		'date-fns',
		'embla-carousel-react',
		'input-otp',
		'lucide-react',
		'nanoid',
		'next-themes',
		'nuqs',
		'react-day-picker',
		'react-hook-form',
		'react-resizable-panels',
		'recharts',
		'sonner',
		'tailwind-merge',
		'vaul',
		'zod',
		'lexical',
		'@lexical/code',
		'@lexical/link',
		'@lexical/list',
		'@lexical/markdown',
		'@lexical/react',
		'@lexical/rich-text',
		'@lexical/selection',
		'@lexical/utils',
		'@monaco-editor/react',
		'@hookform/resolvers',
	],
	esbuildOptions(options) {
		options.jsx = 'automatic'
		options.alias = {
			'@': resolve(__dirname, './src'),
		}
	},
})
