// @ts-nocheck
import * as __fd_glob_60 from "../content/docs/plugins/stripe.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/plugins/seo.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/plugins/sentry.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/plugins/polar.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/plugins/playground.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/plugins/index.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/migrations/migration-files.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/migrations/index.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/migrations/configuration.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/migrations/cli-commands.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/migrations/best-practices.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/getting-started/quick-start.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/getting-started/configuration.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/guides/nextjs-integration.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/guides/auto-save-and-read-only.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/client/ui.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/client/index.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/client/admin.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/core/webhooks-module.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/core/vault-module.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/core/storage-module.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/core/settings-module.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/core/rbac-module.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/core/notifications-module.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/core/index.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/core/email-module.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/core/database-module.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/core/content-module.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/core/cache-module.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/core/auth-module.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/core/api-keys-module.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/core/admin-module.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/common/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/common/field-decorators.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/common/decorators.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/admin/i18n.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/adapters/supabase.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/adapters/storage-s3.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/adapters/storage-r2.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/adapters/mongoose.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/adapters/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/adapters/hashicorp-vault.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/adapters/graphql.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/adapters/email-resend.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/adapters/email-nodemailer.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/adapters/drizzle.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/adapters/cache-redis.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/adapters/auth-clerk.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/plugins/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/migrations/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/core/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/common/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/client/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/admin/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/adapters/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "adapters/meta.json": __fd_glob_1, "admin/meta.json": __fd_glob_2, "client/meta.json": __fd_glob_3, "common/meta.json": __fd_glob_4, "core/meta.json": __fd_glob_5, "getting-started/meta.json": __fd_glob_6, "guides/meta.json": __fd_glob_7, "migrations/meta.json": __fd_glob_8, "plugins/meta.json": __fd_glob_9, }, {"index.mdx": __fd_glob_10, "adapters/auth-clerk.mdx": __fd_glob_11, "adapters/cache-redis.mdx": __fd_glob_12, "adapters/drizzle.mdx": __fd_glob_13, "adapters/email-nodemailer.mdx": __fd_glob_14, "adapters/email-resend.mdx": __fd_glob_15, "adapters/graphql.mdx": __fd_glob_16, "adapters/hashicorp-vault.mdx": __fd_glob_17, "adapters/index.mdx": __fd_glob_18, "adapters/mongoose.mdx": __fd_glob_19, "adapters/storage-r2.mdx": __fd_glob_20, "adapters/storage-s3.mdx": __fd_glob_21, "adapters/supabase.mdx": __fd_glob_22, "admin/i18n.mdx": __fd_glob_23, "common/decorators.mdx": __fd_glob_24, "common/field-decorators.mdx": __fd_glob_25, "common/index.mdx": __fd_glob_26, "core/admin-module.mdx": __fd_glob_27, "core/api-keys-module.mdx": __fd_glob_28, "core/auth-module.mdx": __fd_glob_29, "core/cache-module.mdx": __fd_glob_30, "core/content-module.mdx": __fd_glob_31, "core/database-module.mdx": __fd_glob_32, "core/email-module.mdx": __fd_glob_33, "core/index.mdx": __fd_glob_34, "core/notifications-module.mdx": __fd_glob_35, "core/rbac-module.mdx": __fd_glob_36, "core/settings-module.mdx": __fd_glob_37, "core/storage-module.mdx": __fd_glob_38, "core/vault-module.mdx": __fd_glob_39, "core/webhooks-module.mdx": __fd_glob_40, "client/admin.mdx": __fd_glob_41, "client/index.mdx": __fd_glob_42, "client/ui.mdx": __fd_glob_43, "guides/auto-save-and-read-only.mdx": __fd_glob_44, "guides/nextjs-integration.mdx": __fd_glob_45, "getting-started/configuration.mdx": __fd_glob_46, "getting-started/index.mdx": __fd_glob_47, "getting-started/installation.mdx": __fd_glob_48, "getting-started/quick-start.mdx": __fd_glob_49, "migrations/best-practices.mdx": __fd_glob_50, "migrations/cli-commands.mdx": __fd_glob_51, "migrations/configuration.mdx": __fd_glob_52, "migrations/index.mdx": __fd_glob_53, "migrations/migration-files.mdx": __fd_glob_54, "plugins/index.mdx": __fd_glob_55, "plugins/playground.mdx": __fd_glob_56, "plugins/polar.mdx": __fd_glob_57, "plugins/sentry.mdx": __fd_glob_58, "plugins/seo.mdx": __fd_glob_59, "plugins/stripe.mdx": __fd_glob_60, });